// src/components/budget/TransactionForm.svelte
<script>
  import { dateUtils } from 'src/api/dateUtils';
  import { signal } from "src/api/signal";
  import { budgetApi } from "src/api/budgetApi.svelte.js";
  import { onMount, onDestroy } from 'svelte';
  import { recurringApi } from '/src/api/recurringApi.svelte';

  const signalSubId = "TransactionFormComponent";

  let isNewTransaction = $state(true);
  
  let id = $state('');
  let type = $state('expenses');
  let date = $state();
  let description = $state('');
  let amount = $state('');
  let category = $state('');
  let status = $state('pending');

  let isOpen = $state(false);
  onMount(() => {
    signal.sub("OPEN_TRANSACTION_FORM", signalSubId, (data) => {
      isOpen = true;
      let transaction = data.transaction;
      if (transaction) {
        id = transaction.id;
        type = transaction.type;
        date = transaction.date;
        description = transaction.description;
        amount = transaction.amount;
        category = transaction.category;
        status = transaction.status;
        isNewTransaction = transaction.id === null;
      }
    });
  })
  onDestroy(() => {
    signal.unsubAll(signalSubId);
  });
  
  function handleClose() {
    isOpen = false;
    type = 'expenses';
    date = '';
    description = '';
    amount = '';
    category = '';
  }

  async function handleSubmit(e) {
    e.preventDefault();
    let transaction = { id, type, date, description, amount: parseFloat(amount), category, status };
    let exists = budgetApi.getTransactionById(id) !== undefined;
    if (exists) {
      let existingTransaction = budgetApi.getTransactionById(id);
      if (existingTransaction) Object.assign(existingTransaction, transaction);
      budgetApi.updateTransaction(id);
      signal.emit("UPDATE_TRANSACTION", { transaction: existingTransaction });
    } 
    else {

      if(transaction.id.startsWith("_recurring_")){
        const expenseId = transaction.id.substring("_recurring_".length)
        const recurringExpense = recurringApi.getById(expenseId);
        recurringExpense.excludedDates.push(transaction.date);
        recurringApi.update(expenseId);

        transaction.id = crypto.randomUUID();
        transaction.category = "Recurring Expenses";
      }

      budgetApi.addTransaction(transaction);
      signal.emit("UPDATE_TRANSACTION", { transaction });
    }
    handleClose();
  }
</script>

{#if isOpen}
  <!-- Backdrop -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div
    class="fixed inset-0 bg-black/40 dark:bg-black/60 flex items-center justify-center z-50 p-4"
    onkeydown={(e) => e.key === 'Escape' && handleClose()}
    onclick={(e) => e.target === e.currentTarget && handleClose()}
  >
    <!-- Modal -->
    <div class="w-full max-w-md bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-xl p-5">
      <h3 class="text-base font-bold text-zinc-900 dark:text-zinc-100 mb-4">
        {isNewTransaction ? 'New' : 'Edit'} Transaction
      </h3>
      
      <form onsubmit={handleSubmit} class="space-y-3">
        <div class="grid grid-cols-2 gap-3">
          <label class="flex flex-col gap-1">
            <span class="text-xs font-medium text-zinc-500 dark:text-zinc-400">Type</span>
            <select
              bind:value={type}
              class="px-3 py-2 text-sm border rounded-lg transition-colors cursor-pointer
                {type === 'incomes'
                  ? 'border-emerald-200 dark:border-emerald-800 bg-emerald-50 dark:bg-emerald-950/50 text-emerald-700 dark:text-emerald-300'
                  : 'border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-950/50 text-red-700 dark:text-red-300'
                }"
            >
              <option value="incomes">Income</option>
              <option value="expenses">Expense</option>
            </select>
          </label>
          
          <label class="flex flex-col gap-1">
            <span class="text-xs font-medium text-zinc-500 dark:text-zinc-400">Date</span>
            <input
              type="date"
              bind:value={date}
              class="px-3 py-2 text-sm border border-zinc-200 dark:border-zinc-700 rounded-lg bg-white dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-colors"
            />
          </label>
        </div>
        
        <label class="flex flex-col gap-1">
          <span class="text-xs font-medium text-zinc-500 dark:text-zinc-400">Description</span>
          <input
            type="text"
            bind:value={description}
            placeholder="e.g. Groceries, Salary"
            class="px-3 py-2 text-sm border border-zinc-200 dark:border-zinc-700 rounded-lg bg-white dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100 placeholder-zinc-400 dark:placeholder-zinc-500 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-colors"
            required
          />
        </label>
        
        <div class="grid grid-cols-2 gap-3">
          <label class="flex flex-col gap-1">
            <span class="text-xs font-medium text-zinc-500 dark:text-zinc-400">Amount ($)</span>
            <input
              type="number"
              bind:value={amount}
              placeholder="0.00"
              step="0.01"
              min="0.01"
              class="px-3 py-2 text-sm border border-zinc-200 dark:border-zinc-700 rounded-lg bg-white dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100 placeholder-zinc-400 dark:placeholder-zinc-500 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-colors"
              required
            />
          </label>
          
          <label class="flex flex-col gap-1">
            <span class="text-xs font-medium text-zinc-500 dark:text-zinc-400">Category</span>
            <input
              type="text"
              bind:value={category}
              placeholder="Optional"
              class="px-3 py-2 text-sm border border-zinc-200 dark:border-zinc-700 rounded-lg bg-white dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100 placeholder-zinc-400 dark:placeholder-zinc-500 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-colors"
            />
          </label>
        </div>
        
        <div class="flex justify-end gap-2 pt-2">
          <button
            type="button"
            onclick={handleClose}
            class="px-3 py-1.5 text-sm font-medium text-zinc-600 dark:text-zinc-300 rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors cursor-pointer"
          >
            Cancel
          </button>
          <button
            type="submit"
            class="px-4 py-1.5 text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 dark:bg-indigo-500 dark:hover:bg-indigo-600 rounded-lg active:scale-[0.98] transition-all cursor-pointer"
          >
            {isNewTransaction ? 'Add' : 'Save'}
          </button>
        </div>
      </form>
    </div>
  </div>
{/if}

// src/components/TransactionForm.jsx
import { useState, useEffect } from 'react';
import { getWeekNumber, getWeekDateRange } from '../utils';

const TransactionForm = ({ currentMonth, currentYear, currentWeekNumber, onAdd, onClose, setError }) => {
  const [description, setDescription] = useState('');
  const [amount, setAmount] = useState('');
  const [type, setType] = useState('incomes');
  const [date, setDate] = useState(() => {
    const { start } = getWeekDateRange(currentYear, currentWeekNumber);
    return start.toISOString().substring(0, 10);
  });
  const [targetWeek, setTargetWeek] = useState(currentWeekNumber);

  // Update target week when date changes
  useEffect(() => {
    const selectedDate = new Date(date);
    const newWeekNumber = getWeekNumber(selectedDate);
    setTargetWeek(newWeekNumber);
  }, [date]);
  const [category, setCategory] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    const parsedAmount = parseFloat(amount);
    if (!description || parsedAmount <= 0 || !date || isNaN(parsedAmount)) {
      setError('Please fill in a description, a valid date, and a positive amount.');
      return;
    }
    setError(null);
    const newTransaction = {
      date,
      description,
      amount: parsedAmount,
      category: category || null,
      status: 'pending',
    };
    onAdd(currentYear, currentMonth, targetWeek, type, newTransaction);
    onClose();
  };

  return (
    <div className="p-6 bg-white dark:bg-gray-800 rounded-xl shadow-2xl space-y-4">
      <h3 className="text-xl font-bold text-gray-900 dark:text-white border-b border-gray-200 dark:border-gray-700 pb-2">
        Add Transaction to W{targetWeek}
        {targetWeek !== currentWeekNumber && (
          <p className="text-sm text-amber-600 dark:text-amber-400 mt-1">
            Note: Transaction will be added to week {targetWeek} based on selected date
          </p>
        )}
      </h3>
      <form onSubmit={handleSubmit} className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <label className="flex flex-col">
            <span className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Type</span>
            <select
              value={type}
              onChange={e => setType(e.target.value)}
              className={`p-2 border rounded-lg focus:ring-2 transition ${type === 'incomes' ? 'bg-green-50 text-green-800 border-green-300 focus:ring-green-500 dark:bg-green-900/50 dark:text-green-300 dark:border-green-700' : 'bg-red-50 text-red-800 border-red-300 focus:ring-red-500 dark:bg-red-900/50 dark:text-red-300 dark:border-red-700'} dark:bg-gray-700 dark:text-white dark:border-gray-600`}
            >
              <option value="incomes">Income</option>
              <option value="expenses">Expense</option>
            </select>
          </label>
          <label className="flex flex-col">
            <span className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Date</span>
            <input
              type="date"
              value={date}
              onChange={e => setDate(e.target.value)}
              className="p-2 border border-gray-300 dark:border-gray-600 rounded-lg dark:bg-gray-700 dark:text-white focus:ring-indigo-500 focus:border-indigo-500 transition"
            />
          </label>
        </div>
        <label className="flex flex-col">
          <span className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Description</span>
          <input
            type="text"
            value={description}
            onChange={e => setDescription(e.target.value)}
            placeholder="e.g., Groceries, Salary, Rent"
            className="p-2 border border-gray-300 dark:border-gray-600 rounded-lg dark:bg-gray-700 dark:text-white focus:ring-indigo-500 focus:border-indigo-500 transition"
            required
          />
        </label>
        <div className="grid grid-cols-2 gap-4">
          <label className="flex flex-col">
            <span className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Amount ($)</span>
            <input
              type="number"
              value={amount}
              onChange={e => setAmount(e.target.value)}
              placeholder="0.00"
              step="0.01"
              min="0.01"
              className="p-2 border border-gray-300 dark:border-gray-600 rounded-lg dark:bg-gray-700 dark:text-white focus:ring-indigo-500 focus:border-indigo-500 transition"
              required
            />
          </label>
          <label className="flex flex-col">
            <span className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Category (Optional)</span>
            <input
              type="text"
              value={category}
              onChange={e => setCategory(e.target.value)}
              placeholder="e.g., Food, Travel"
              className="p-2 border border-gray-300 dark:border-gray-600 rounded-lg dark:bg-gray-700 dark:text-white focus:ring-indigo-500 focus:border-indigo-500 transition"
            />
          </label>
        </div>
        <div className="flex justify-end space-x-3 pt-2">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-gray-600 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 rounded-xl hover:bg-gray-200 dark:hover:bg-gray-600 transition"
          >
            Cancel
          </button>
          <button
            type="submit"
            className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-xl shadow-lg hover:bg-indigo-700 transition"
          >
            Add Transaction
          </button>
        </div>
      </form>
    </div>
  );
};

export default TransactionForm;
