// src/components/WeekCard.svelte
<script>
  import { dateUtils } from '../api/dateUtils.js';
  import { Plus } from 'lucide-svelte';
  
  let props = $props();
  let weekNumber = props.weekNumber ?? 1;
  let currentMonth = props.currentMonth ?? 1;
  let currentYear = props.currentYear ?? 2023;

  let cardStyles = "bg-white dark:bg-gray-800 p-4 rounded-xl shadow-md dark:shadow-lg dark:shadow-black/20 sticky top-0 z-10 border border-gray-100 dark:border-gray-700/50";
  let dateRange = dateUtils.getWeekDateRange(currentYear, weekNumber);

  function openAddItemModal() {
    // Placeholder function for opening a modal to add a new item
    console.log(`Open modal to add new item for Week ${weekNumber}`);
  }
</script>

<article class="flex {cardStyles}">
  <header class="flex items-center justify-between w-full pb-3 mb-4 border-b border-gray-200 dark:border-gray-700">
    <div>
      <h2 class="font-extrabold">{dateRange[0].toLocaleString('default', { month: 'short' })} {dateRange[0].getDate()} – {dateRange[6].toLocaleString('default', { month: 'short' })} {dateRange[6].getDate()}</h2>
      <p class="text-sm text-gray-500 dark:text-gray-400">W{weekNumber}</p>
    </div>
    <button
      class="flex items-center space-x-1 px-3 py-1.5 text-sm font-medium text-white rounded-xl shadow-md transition-all duration-300
      bg-gradient-to-r from-indigo-600 to-purple-600 dark:from-indigo-500 dark:to-purple-500 hover:brightness-110 cursor-pointer"
      aria-label="Add new item for this week"
      style="background-clip: padding-box;"
      title="Add Transaction"
      onclick={openAddItemModal}
    >
      <Plus size={18}/>
      <span class="hidden sm:inline">Add</span>
    </button>
  </header>
</article>

// src/components/WeekCard.jsx
import { useMemo, useState } from 'react';
import TransactionList from './TransactionList';
import TransactionForm from './TransactionForm';
import { calculateWeeklyTotals, formatCurrency } from '../utils';
import { Plus } from 'lucide-react';

const WeekCard = ({ week, currentYear, currentMonth, onAddTransaction, onRemoveTransaction, onToggleStatus, setError }) => {
  const totals = useMemo(() => calculateWeeklyTotals(week), [week]);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const netColor = totals.net >= 0 ? 'text-green-500 dark:text-green-400' : 'text-red-500 dark:text-red-400';

  return (
    <div className="bg-white dark:bg-gray-800 p-5 rounded-xl shadow-lg border border-gray-100 dark:border-gray-700/50">
      <div className="flex justify-between items-center border-b pb-3 mb-4 border-gray-200 dark:border-gray-700">
        <div>
          <h3 className="text-xl font-extrabold text-gray-900 dark:text-white">W{week.weekNumber}</h3>
          <p className="text-sm text-gray-500 dark:text-gray-400">{week.dateRange}</p>
        </div>
        <button
          onClick={() => setIsFormOpen(true)}
          className="flex items-center space-x-1 px-3 py-1.5 text-sm font-medium text-white bg-indigo-600 rounded-xl shadow-md hover:bg-indigo-700 transition"
          title="Add Transaction"
        >
          <Plus size={18} />
          <span className="hidden sm:inline">Add</span>
        </button>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <TransactionList
          transactions={week.incomes}
          type="incomes"
          weekNumber={week.weekNumber}
          currentYear={currentYear}
          currentMonth={currentMonth}
          onRemove={onRemoveTransaction}
          onToggleStatus={onToggleStatus}
          setError={setError}
        />
        <TransactionList
          transactions={week.expenses}
          type="expenses"
          weekNumber={week.weekNumber}
          currentYear={currentYear}
          currentMonth={currentMonth}
          onRemove={onRemoveTransaction}
          onToggleStatus={onToggleStatus}
          setError={setError}
        />
      </div>
      <div className="mt-5 pt-4 border-t border-gray-200 dark:border-gray-700 flex justify-between items-center text-sm font-semibold">
        <span className="text-gray-600 dark:text-gray-300">Weekly Net:</span>
        <span className={`text-lg ${netColor}`}>{formatCurrency(totals.net)}</span>
      </div>
      {isFormOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-50 dark:bg-opacity-70 flex items-center justify-center z-50 p-4">
          <TransactionForm
            currentMonth={currentMonth}
            currentYear={currentYear}
            currentWeekNumber={week.weekNumber}
            onAdd={onAddTransaction}
            onClose={() => setIsFormOpen(false)}
            setError={setError}
          />
        </div>
      )}
    </div>
  );
};

export default WeekCard;
